<a href="https://colab.research.google.com/github/anitadala/DeepLearningPrerequisites/blob/master/DeepLearningPrerequisites.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Arrays vs Lists
import numpy as np


In [2]:
#Lists in python
L = [1,2,3]
L

[1, 2, 3]

In [4]:
#Arrays in numpy
A = np.array([1,2,3])
A

array([1, 2, 3])

In [5]:
L = L + [4]
L

[1, 2, 3, 4]

In [6]:
A = A + np.array([4])
A
#As we can see in numpy 4 is added to eah element of the array
#it does not appended or concatenated to the array like in lists do.


array([5, 6, 7])

In [ ]:
L.append(5)
L
#size of a list can change but size of an array is fixed

In [12]:
A = A + np.array([2,2,3])
A
#elements are added individually to the array elements

array([ 7,  8, 10])

In [13]:
#Scaler Multiplication
2*A


array([14, 16, 20])

In [20]:
L = 2 * [1,2,3]
#It seems like the list multiply the occurances of the elements present in it

[1, 2, 3, 1, 2, 3]

In [23]:
L2= []
for e in L:
  L2.append(e+3)
L2
#for adding a particular number to each element of the list

[4, 5, 6, 4, 5, 6]

In [25]:
#Squaring each element in np array vs lists
#np.arrays:
A**2
#LISTS
l2=[]
for e in L:
  l2.append(e**2)
l2

[1, 4, 9, 1, 4, 9]

In [26]:
np.sqrt(A)

array([2.64575131, 2.82842712, 3.16227766])

In [27]:
np.log(A)

array([1.94591015, 2.07944154, 2.30258509])

In [28]:
np.exp(A)

array([ 1096.63315843,  2980.95798704, 22026.46579481])

In [29]:
np.tanh(A)

array([0.99999834, 0.99999977, 1.        ])

In [ ]:
#Sum Up:
#A lists looks like an array but it is more like an generic data structure
#while a numpy array is specifically used to do math

#DOT PRODUCT

In [33]:
A = np.array([1,2])
B = np.array([3,4])

In [35]:
dot = 0
for e,f in zip(A,B):
  dot += e*f

dot

11

In [36]:
A*B

array([3, 8])

In [37]:
np.sum(A*B)

11

In [39]:
np.dot(A,B)

11

In [40]:
A.dot(B)

11

In [41]:
A@B

11

In [43]:
#we can find out the magnitude of an vector 
mag = np.sqrt((A*A).sum())
mag

2.23606797749979

In [44]:
#or by using:
np.linalg.norm(A)

2.23606797749979

In [46]:
cosanglebwAandB = A.dot(B)/(np.linalg.norm(A)*np.linalg.norm(B))
cosanglebwAandB 

0.9838699100999074

# Speed Test